{
    'name': 'Travel Pro',
    'version': '18.0.1.0.0',
    'category': 'Travel',
    'summary': 'Gestion agence de voyage We Can Travel',
    'author': 'Rayeen',
    'depends': ['base', 'sale', 'account', 'purchase', 'stock', 'point_of_sale', 'purchase_stock'],
    'data': [
        'data/reservation_sequence.xml',
        'data/voyage_sequence.xml',
        'data/statistic_data.xml',
        'data/guide_data.xml',
        'security/ir.model.access.csv',
        'views/menu_root.xml', # Re-ajouté ici (essentiel !)
        'views/guide_views.xml',
        'views/client_views.xml',
        'views/destination_views.xml',
        'views/voyage_views.xml',
        'views/account_move_views.xml',
        'views/accounting_views.xml',
        'views/reservation_views.xml',
        'views/logistique_views.xml',
        'views/statistic_views.xml',
        'views/purchase_views.xml',
        'views/caisse_views.xml',
        'views/stock_views.xml',
        'views/sale_order_views.xml',
        'views/actions.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
