from . import client
from . import destination
from . import voyage
from . import voyage_jour
from . import voyage_transport
from . import voyage_hotel
from . import voyage_restauration
from . import voyage_guide
from . import voyage_equipement
from . import reservation_passager
from . import reservation
from . import statistic
from . import account_move
from . import caisse
from . import sale_order
from . import guide
